config/routes.rb
Rails
  .application
  .routes
  .draw do
    root to: 'products#index'
    resources :products
    namespace :api, defaults: { format: :json } do
      namespace :v1 do
        resources :products do
          resources :reviews, only: %i[index create]
        end
      end
    end
    mount ActionCable.server, at: '/cable'
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates :product_id, :content, :rating, presence: true
end

app/controllers/api/v1/reviews_controller.rb
class Api::V1::ReviewsController < ApplicationController
  protect_from_forgery with: :null_session

  def index
    @product = Product.find(params[:product_id])
    @reviews = @product.reviews
    render json: @reviews
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.build(review_params)
    respond_to do |format|
      if @review.save
        ActionCable.server.broadcast("reviews_for_product_#{params[:product_id]}", @review)
        format.json { render json: @review, status: :created }
      else
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating, :product_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="is-size-6-mobile">
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' unless Webpacker.config.dev_server and Webpacker.config.dev_server[:hmr] %>
    <%= javascript_packs_with_chunks_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="section">
      <div class="container">
        <%= yield %>
      </div>
    </section>
  </body>
</html>

app/views/products/index.html.erb
<h1 class="title">Products</h1>

<ul class="columns is-multiline">
  <% @products.each do |product| %>
    <li class="column is-half is-flex">
      <%= link_to product_path(product), class: "box is-flex is-flex-direction-column is-justify-content-space-between is-full-width" do %>
        <h2 class="title is-4"><%= product.title %></h2>
          <div class="block is-flex-grow-5 is-flex is-flex-direction-column is-justify-content-flex-start">
            <p class="subtitle"><%= product.blurb %></p>
          </div>
        <div class="has-text-primary has-text-weight-bold is-flex is-justify-content-space-between is-align-items-center">
          <span class="is-size-5">See details</span>
          <span class="is-size-3">›</span>
        </div>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/products/show.html.erb
<h1 class="title"><%= @product.title %></h1>
<p class="block subtitle"><%= @product.blurb %></p>
<p class="block"><%= @product.description %></p>

<div id="reviews-react" data-product-id="<%= @product.id %>">
  <b>Loading reviews...</b>
  <div class="no-react"></div>
</div>
<%= javascript_packs_with_chunks_tag 'react-reviews', 'data-turbolinks-track': 'reload' %>